http:
  host: 127.0.0.1
  port: 8080

influxdb:
  host: 10.0.10.70
  port: 18901
  dbName: mirror_status
  password: deepinadmin
  username: admin

mysql:
  host: client
  port: 3306
  dbName: mirror_status
  username: root
  password: admin

cdn-checker:
  # Default CDN URL without HTTP/HTTPS header
  default-cdn: cdn.packages.deepin.com
  # Simulating browser
  user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36"
  # URL of checker API provider, used for user login
  api-site: https://www.17ce.com
  # URL path of checker API
  api-path: /site/checkuser
  # URL for fetching mirror info in JSON format
  target: http://server-12:8900/v1/mirrors
  # URL for storing source packages
  source-url: http://packages.deepin.com/deepin/
  # URL path to get source change list
  source-path: changelist/

ldap:
  server: 0.ldap.sndu.cn
  port: 636
  bind_dn: cn=cms,ou=manage,dc=sndu,dc=cn
  bind_passwd: 4w#WgAv9Q%
  user_search: ou=people,dc=sndu,dc=cn
  group_search: cn=logs,ou=group,dc=sndu,dc=cn

jenkins:
  addr: https://ci.deepin.io
  trigger: dstore-mirror-json token

mail:
  host: smtp.exmail.qq.com
  port: 465
  username: zhaojuwen@deepin.com
  password: ckv2cFb2DGdFeqhX

redis:
  host: localhost
  port: 6379
  username:
  password:
  db: 0