http:
  host:
  port:

influxdb:
  host:
  port:
  dbName:
  password:
  username:

mysql:
  host:
  port:
  dbName:
  username:
  password:

cdn-checker:
  default-cdn:
  user-agent:
  api-site:
  api-path:
  target:
  source-url:
  source-path: