http:
  host: 127.0.0.1
  port: 8080

influxdb:
  host: 127.0.0.1
  port: 5432
  dbName: influx
  password: deepin
  username: admin

mysql:
  host: 127.0.0.1
  port: 3306
  dbName: mysql
  username: deepin
  password: admin

cdn-checker:
  # Default CDN URL without HTTP/HTTPS header
  default-cdn: cdn.packages.deepin.com
  # Simulating browser
  user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36"
  # URL of checker API provider, used for user login
  api-site: https://www.17ce.com
  # URL path of checker API
  api-path: /site/checkuser
  # URL for fetching mirror info in JSON format
  target: http://server-12:8900/v1/mirrors
  # URL for storing source packages
  source-url: http://packages.deepin.com/deepin/
  # URL path to get source change list
  source-path: changelist/

# LDAP configs
ldap:
  server: 0.ldap.deepin.cn
  port: 636
  bind-dn: cn=cms,ou=manage,dc=sndu,dc=cn
  bind-passwd: password
  user-search: search

# Trigger information related to jenkins.yml
jenkins:
  addr: https://ci.deepin.io
  trigger: dstore-mirror-json token
  delay: 2
  retry: 3

# Mail proxy configs
mail:
  host: smtp.exmail.qq.com
  port: 465
  username: example@deepin.com
  # Credential but not password of mail account
  password: password

# Redis config
redis:
  host: localhost
  port: 6379