http:
  host: 127.0.0.1
  port: 8080

influxdb:
  host: 10.0.10.70
  port: 18901
  dbName: mirror_status
  password: deepinadmin
  username: admin

mysql:
  host: db
  port: 3306
  dbName: mirror_status
  username: root
  password: admin

cdn-checker:
  # Default CDN URL without HTTP/HTTPS header
  default-cdn: cdn.packages.deepin.com
  # Simulating browser
  user-agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36"
  # URL of checker API provider, used for user login
  api-site: https://www.17ce.com
  # URL path of checker API
  api-path: /site/checkuser
  # URL for fetching mirror info in JSON format
  target: http://server-12:8900/v1/mirrors
  # URL for storing source packages
  source-url: http://packages.deepin.com/deepin/
  # URL path to get source change list
  source-path: changelist/